[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
monitor_speed = 921600
build_unflags = -Os
build_flags = 
	-O3
	-funroll-loops 
    -ffast-math
	-I.pio/build/rpipico2/pioasm
lib_deps = etherkit/Etherkit Si5351@^2.2.0